export const categories = [
  { label: 'Business', code: 'business' },
  { label: 'Crime', code: 'crime' },
  { label: 'Domestic', code: 'domestic' },
  { label: 'Education', code: 'education' },
  { label: 'Entertainment', code: 'entertainment' },
  { label: 'Environment', code: 'environment' },
  { label: 'Food', code: 'food' },
  { label: 'Health', code: 'health' },
  { label: 'Lifestyle', code: 'lifestyle' },
  { label: 'Other', code: 'other' },
  { label: 'Politics', code: 'politics' },
  { label: 'Science', code: 'science' },
  { label: 'Sports', code: 'sports' },
  { label: 'Technology', code: 'technology' },
  { label: 'Top', code: 'top' },
  { label: 'Tourism', code: 'tourism' },
  { label: 'World', code: 'world' },
];

export const countries = [
  { label: 'Afghanistan', code: 'af' },
  { label: 'Albania', code: 'al' },
  { label: 'Algeria', code: 'dz' },
  { label: 'Andorra', code: 'ad' },
  { label: 'Angola', code: 'ao' },
  { label: 'Argentina', code: 'ar' },
  { label: 'Armenia', code: 'am' },
  { label: 'Australia', code: 'au' },
  { label: 'Austria', code: 'at' },
  { label: 'Azerbaijan', code: 'az' },
  { label: 'Bahamas', code: 'bs' },
  { label: 'Bahrain', code: 'bh' },
  { label: 'Bangladesh', code: 'bd' },
  { label: 'Barbados', code: 'bb' },
  { label: 'Belarus', code: 'by' },
  { label: 'Belgium', code: 'be' },
  { label: 'Belize', code: 'bz' },
  { label: 'Benin', code: 'bj' },
  { label: 'Bermuda', code: 'bm' },
  { label: 'Bhutan', code: 'bt' },
  { label: 'Bolivia', code: 'bo' },
  { label: 'Bosnia And Herzegovina', code: 'ba' },
  { label: 'Botswana', code: 'bw' },
  { label: 'Brazil', code: 'br' },
  { label: 'Brunei', code: 'bn' },
  { label: 'Bulgaria', code: 'bg' },
  { label: 'Burkina Faso', code: 'bf' },
  { label: 'Burundi', code: 'bi' },
  { label: 'Cambodia', code: 'kh' },
  { label: 'Cameroon', code: 'cm' },
  { label: 'Canada', code: 'ca' },
  { label: 'Cape Verde', code: 'cv' },
  { label: 'Cayman Islands', code: 'ky' },
  { label: 'Central African Republic', code: 'cf' },
  { label: 'Chad', code: 'td' },
  { label: 'Chile', code: 'cl' },
  { label: 'China', code: 'cn' },
  { label: 'Colombia', code: 'co' },
  { label: 'Comoros', code: 'km' },
  { label: 'Congo', code: 'cg' },
  { label: 'Cook Islands', code: 'ck' },
  { label: 'Costa Rica', code: 'cr' },
  { label: 'Croatia', code: 'hr' },
  { label: 'Cuba', code: 'cu' },
  { label: 'Curaçao', code: 'cw' },
  { label: 'Cyprus', code: 'cy' },
  { label: 'Czech Republic', code: 'cz' },
  { label: 'Denmark', code: 'dk' },
  { label: 'Djibouti', code: 'dj' },
  { label: 'Dominica', code: 'dm' },
  { label: 'Dominican Republic', code: 'do' },
  { label: 'DR Congo', code: 'cd' },
  { label: 'Ecuador', code: 'ec' },
  { label: 'Egypt', code: 'eg' },
  { label: 'El Salvador', code: 'sv' },
  { label: 'Equatorial Guinea', code: 'gq' },
  { label: 'Eritrea', code: 'er' },
  { label: 'Estonia', code: 'ee' },
  { label: 'Eswatini', code: 'sz' },
  { label: 'Ethiopia', code: 'et' },
  { label: 'Fiji', code: 'fj' },
  { label: 'Finland', code: 'fi' },
  { label: 'France', code: 'fr' },
  { label: 'French Polynesia', code: 'pf' },
  { label: 'Gabon', code: 'ga' },
  { label: 'Gambia', code: 'gm' },
  { label: 'Georgia', code: 'ge' },
  { label: 'Germany', code: 'de' },
  { label: 'Ghana', code: 'gh' },
  { label: 'Gibraltar', code: 'gi' },
  { label: 'Greece', code: 'gr' },
  { label: 'Grenada', code: 'gd' },
  { label: 'Guatemala', code: 'gt' },
  { label: 'Guinea', code: 'gn' },
  { label: 'Guyana', code: 'gy' },
  { label: 'Haiti', code: 'ht' },
  { label: 'Honduras', code: 'hn' },
  { label: 'Hong Kong', code: 'hk' },
  { label: 'Hungary', code: 'hu' },
  { label: 'Iceland', code: 'is' },
  { label: 'India', code: 'in' },
  { label: 'Indonesia', code: 'id' },
  { label: 'Iran', code: 'ir' },
  { label: 'Iraq', code: 'iq' },
  { label: 'Ireland', code: 'ie' },
  { label: 'Israel', code: 'il' },
  { label: 'Italy', code: 'it' },
  { label: 'Ivory Coast', code: 'ci' },
  { label: 'Jamaica', code: 'jm' },
  { label: 'Japan', code: 'jp' },
  { label: 'Jersey', code: 'je' },
  { label: 'Jordan', code: 'jo' },
  { label: 'Kazakhstan', code: 'kz' },
  { label: 'Kenya', code: 'ke' },
  { label: 'Kiribati', code: 'ki' },
  { label: 'Kosovo', code: 'xk' },
  { label: 'Kuwait', code: 'kw' },
  { label: 'Kyrgyzstan', code: 'kg' },
  { label: 'Laos', code: 'la' },
  { label: 'Latvia', code: 'lv' },
  { label: 'Lebanon', code: 'lb' },
  { label: 'Lesotho', code: 'ls' },
  { label: 'Liberia', code: 'lr' },
  { label: 'Libya', code: 'ly' },
  { label: 'Liechtenstein', code: 'li' },
  { label: 'Lithuania', code: 'lt' },
  { label: 'Luxembourg', code: 'lu' },
  { label: 'Macau', code: 'mo' },
  { label: 'Macedonia', code: 'mk' },
  { label: 'Madagascar', code: 'mg' },
  { label: 'Malawi', code: 'mw' },
  { label: 'Malaysia', code: 'my' },
  { label: 'Maldives', code: 'mv' },
  { label: 'Mali', code: 'ml' },
  { label: 'Malta', code: 'mt' },
  { label: 'Marshall Islands', code: 'mh' },
  { label: 'Mauritania', code: 'mr' },
  { label: 'Mauritius', code: 'mu' },
  { label: 'Mexico', code: 'mx' },
  { label: 'Micronesia', code: 'fm' },
  { label: 'Moldova', code: 'md' },
  { label: 'Monaco', code: 'mc' },
  { label: 'Mongolia', code: 'mn' },
  { label: 'Montenegro', code: 'me' },
  { label: 'Morocco', code: 'ma' },
  { label: 'Mozambique', code: 'mz' },
  { label: 'Myanmar', code: 'mm' },
  { label: 'Namibia', code: 'na' },
  { label: 'Nauru', code: 'nr' },
  { label: 'Nepal', code: 'np' },
  { label: 'Netherland', code: 'nl' },
  { label: 'New Caledonia', code: 'nc' },
  { label: 'New Zealand', code: 'nz' },
  { label: 'Nicaragua', code: 'ni' },
  { label: 'Niger', code: 'ne' },
  { label: 'Nigeria', code: 'ng' },
  { label: 'North Korea', code: 'kp' },
  { label: 'Norway', code: 'no' },
  { label: 'Oman', code: 'om' },
  { label: 'Pakistan', code: 'pk' },
  { label: 'Palau', code: 'pw' },
  { label: 'Palestine', code: 'ps' },
  { label: 'Panama', code: 'pa' },
  { label: 'Papua New Guinea', code: 'pg' },
  { label: 'Paraguay', code: 'py' },
  { label: 'Peru', code: 'pe' },
  { label: 'Philippines', code: 'ph' },
  { label: 'Poland', code: 'pl' },
  { label: 'Portugal', code: 'pt' },
  { label: 'Puerto Rico', code: 'pr' },
  { label: 'Qatar', code: 'qa' },
  { label: 'Romania', code: 'ro' },
  { label: 'Russia', code: 'ru' },
  { label: 'Rwanda', code: 'rw' },
  { label: 'Saint Lucia', code: 'lc' },
  { label: 'Saint Martin (Dutch)', code: 'sx' },
  { label: 'Samoa', code: 'ws' },
  { label: 'San Marino', code: 'sm' },
  { label: 'Sao Tome and Principe', code: 'st' },
  { label: 'Saudi Arabia', code: 'sa' },
  { label: 'Senegal', code: 'sn' },
  { label: 'Serbia', code: 'rs' },
  { label: 'Seychelles', code: 'sc' },
  { label: 'Sierra Leone', code: 'sl' },
  { label: 'Singapore', code: 'sg' },
  { label: 'Slovakia', code: 'sk' },
  { label: 'Slovenia', code: 'si' },
  { label: 'Solomon Islands', code: 'sb' },
  { label: 'Somalia', code: 'so' },
  { label: 'South Africa', code: 'za' },
  { label: 'South Korea', code: 'kr' },
  { label: 'Spain', code: 'es' },
  { label: 'Sri Lanka', code: 'lk' },
  { label: 'Sudan', code: 'sd' },
  { label: 'Surilabel', code: 'sr' },
  { label: 'Sweden', code: 'se' },
  { label: 'Switzerland', code: 'ch' },
  { label: 'Syria', code: 'sy' },
  { label: 'Taiwan', code: 'tw' },
  { label: 'Tajikistan', code: 'tj' },
  { label: 'Tanzania', code: 'tz' },
  { label: 'Thailand', code: 'th' },
  { label: 'Timor-Leste', code: 'tl' },
  { label: 'Togo', code: 'tg' },
  { label: 'Tonga', code: 'to' },
  { label: 'Trinidad and Tobago', code: 'tt' },
  { label: 'Tunisia', code: 'tn' },
  { label: 'Turkey', code: 'tr' },
  { label: 'Turkmenistan', code: 'tm' },
  { label: 'Tuvalu', code: 'tv' },
  { label: 'Uganda', code: 'ug' },
  { label: 'Ukraine', code: 'ua' },
  { label: 'United Arab Emirates', code: 'ae' },
  { label: 'United Kingdom', code: 'gb' },
  { label: 'United States of America', code: 'us' },
  { label: 'Uruguay', code: 'uy' },
  { label: 'Uzbekistan', code: 'uz' },
  { label: 'Vanuatu', code: 'vu' },
  { label: 'Vatican', code: 'va' },
  { label: 'Venezuela', code: 've' },
  { label: 'Vietnam', code: 'vi' },
  { label: 'Virgin Islands (British)', code: 'vg' },
  { label: 'World', code: 'wo' },
  { label: 'Yemen', code: 'ye' },
  { label: 'Zambia', code: 'zm' },
  { label: 'Zimbabwe', code: 'zw' },
];

export const languages = [
  { label: 'Afrikaans', code: 'af' },
  { label: 'Albanian', code: 'sq' },
  { label: 'Amharic', code: 'am' },
  { label: 'Arabic', code: 'ar' },
  { label: 'Armenian', code: 'hy' },
  { label: 'Assamese', code: 'as' },
  { label: 'Azerbaijani', code: 'az' },
  { label: 'Bambara', code: 'bm' },
  { label: 'Basque', code: 'eu' },
  { label: 'Belarusian', code: 'be' },
  { label: 'Bengali', code: 'bn' },
  { label: 'Bosnian', code: 'bs' },
  { label: 'Bulgarian', code: 'bg' },
  { label: 'Burmese', code: 'my' },
  { label: 'Catalan', code: 'ca' },
  { label: 'Central Kurdish', code: 'ckb' },
  { label: 'Chinese', code: 'zh' },
  { label: 'Croatian', code: 'hr' },
  { label: 'Czech', code: 'cs' },
  { label: 'Danish', code: 'da' },
  { label: 'Dutch', code: 'nl' },
  { label: 'English', code: 'en' },
  { label: 'Estonian', code: 'et' },
  { label: 'Filipino', code: 'pi' },
  { label: 'Finnish', code: 'fi' },
  { label: 'French', code: 'fr' },
  { label: 'Galician', code: 'gl' },
  { label: 'Georgian', code: 'ka' },
  { label: 'German', code: 'de' },
  { label: 'Greek', code: 'el' },
  { label: 'Gujarati', code: 'gu' },
  { label: 'Hausa', code: 'ha' },
  { label: 'Hebrew', code: 'he' },
  { label: 'Hindi', code: 'hi' },
  { label: 'Hungarian', code: 'hu' },
  { label: 'Icelandic', code: 'is' },
  { label: 'Indonesian', code: 'id' },
  { label: 'Italian', code: 'it' },
  { label: 'Japanese', code: 'jp' },
  { label: 'Kannada', code: 'kn' },
  { label: 'Kazakh', code: 'kz' },
  { label: 'Khmer', code: 'kh' },
  { label: 'Kinyarwanda', code: 'rw' },
  { label: 'Korean', code: 'ko' },
  { label: 'Kurdish', code: 'ku' },
  { label: 'Latvian', code: 'lv' },
  { label: 'Lithuanian', code: 'lt' },
  { label: 'Luxembourgish', code: 'lb' },
  { label: 'Macedonian', code: 'mk' },
  { label: 'Malay', code: 'ms' },
  { label: 'Malayalam', code: 'ml' },
  { label: 'Maltese', code: 'mt' },
  { label: 'Maori', code: 'mi' },
  { label: 'Marathi', code: 'mr' },
  { label: 'Mongolian', code: 'mn' },
  { label: 'Nepali', code: 'ne' },
  { label: 'Norwegian', code: 'no' },
  { label: 'Oriya', code: 'or' },
  { label: 'Pashto', code: 'ps' },
  { label: 'Persian', code: 'fa' },
  { label: 'Polish', code: 'pl' },
  { label: 'Portuguese', code: 'pt' },
  { label: 'Punjabi', code: 'pa' },
  { label: 'Romanian', code: 'ro' },
  { label: 'Russian', code: 'ru' },
  { label: 'Samoan', code: 'sm' },
  { label: 'Serbian', code: 'sr' },
  { label: 'Shona', code: 'sn' },
  { label: 'Sindhi', code: 'sd' },
  { label: 'Sinhala', code: 'si' },
  { label: 'Slovak', code: 'sk' },
  { label: 'Slovenian', code: 'sl' },
  { label: 'Somali', code: 'so' },
  { label: 'Spanish', code: 'es' },
  { label: 'Swahili', code: 'sw' },
  { label: 'Swedish', code: 'sv' },
  { label: 'Tajik', code: 'tg' },
  { label: 'Tamil', code: 'ta' },
  { label: 'Telugu', code: 'te' },
  { label: 'Thai', code: 'th' },
  { label: 'Traditional Chinese', code: 'zht' },
  { label: 'Turkish', code: 'tr' },
  { label: 'Turkmen', code: 'tk' },
  { label: 'Ukrainian', code: 'uk' },
  { label: 'Urdu', code: 'ur' },
  { label: 'Uzbek', code: 'uz' },
  { label: 'Vietlabelse', code: 'vi' },
  { label: 'Welsh', code: 'cy' },
  { label: 'Zulu', code: 'zu' },
];
